create table if not exists prescriptions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  telegram_user_id bigint not null,
  telegram_chat_id bigint not null,
  message_id bigint not null,
  raw_data jsonb not null,
  summary text
);

create index if not exists idx_prescriptions_user on prescriptions(telegram_user_id);
